# Generated by Django 4.1.6 on 2023-02-08 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 7, 47, 27, 642606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 7, 47, 27, 642606, tzinfo=datetime.timezone.utc)),
        ),
    ]
