# Generated by Django 4.1.6 on 2023-02-08 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_date_alter_chapter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 8, 34, 53, 38856, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 8, 34, 53, 38856, tzinfo=datetime.timezone.utc)),
        ),
    ]
