# Generated by Django 4.1.6 on 2023-02-14 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chapter_options_book_user_alter_book_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 15, 41, 14, 661264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 15, 41, 14, 661264, tzinfo=datetime.timezone.utc)),
        ),
    ]
