# Generated by Django 4.1.6 on 2023-03-01 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_date_alter_chapter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 2, 42, 20, 663291, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 2, 42, 20, 663291, tzinfo=datetime.timezone.utc)),
        ),
    ]
