# Generated by Django 4.1.6 on 2023-03-01 06:42

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_book_date_alter_chapter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(default='posts/default.jpg', upload_to=app.models.upload_to, verbose_name='Cover_photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 6, 42, 47, 270923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 6, 42, 47, 271959, tzinfo=datetime.timezone.utc)),
        ),
    ]
